// Plain-text-on-copy guard for selections inside `<pre>` / `<code>`.
//
// The browser's default copy behaviour grabs both text/plain AND a
// styled text/html version of the selection. Pasting that into another
// rich editor (email composer, doc app, chat) brings the code-block
// background, borders and font along for the ride. Code is supposed to
// be plain text — the in-block "Copier" button already serialises via
// textContent for that reason, but manual selection + Ctrl+C / OS copy
// menu went through the default path.
//
// `attachPlainTextCodeCopy(el)` listens for `copy` on `el` and rewrites
// the clipboard payload to plain text whenever both endpoints of the
// selection sit inside the same `<pre>` or `<code>` element. Mixed
// selections (code + surrounding prose) are left alone so the user can
// still copy a paragraph with an inline `code` span and keep the prose
// formatting.

export function attachPlainTextCodeCopy(el) {
  if (!el || typeof el.addEventListener !== "function") {
    return () => {};
  }

  const codeAncestor = (node) => {
    let n = node;
    if (n && n.nodeType === 3) n = n.parentElement;
    return n && typeof n.closest === "function" ? n.closest("pre, code") : null;
  };

  const onCopy = (event) => {
    const sel =
      typeof window !== "undefined" && window.getSelection
        ? window.getSelection()
        : null;
    if (!sel || sel.rangeCount === 0 || sel.isCollapsed) return;
    const range = sel.getRangeAt(0);
    const startCode = codeAncestor(range.startContainer);
    const endCode = codeAncestor(range.endContainer);
    if (!startCode || startCode !== endCode) return;

    const data = event.clipboardData;
    if (!data) return;
    const plain = sel.toString();
    try {
      data.setData("text/plain", plain);
      // Also overwrite text/html so a receiver that prefers HTML
      // doesn't pull the styled fragment the browser would have
      // generated by default.
      data.setData("text/html", plain);
      event.preventDefault();
    } catch (_e) {
      // Some browsers throw when setData is called outside a real
      // user-initiated copy — leave the default behaviour in place.
    }
  };

  el.addEventListener("copy", onCopy);
  return () => el.removeEventListener("copy", onCopy);
}

export default attachPlainTextCodeCopy;
